name: Trigger auto deployment for optimaai-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/optimaai-api-AutoDeployTrigger-33c1482c-b19c-4423-a1e5-2d3b89c03613.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.OPTIMAAIAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OPTIMAAIAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OPTIMAAIAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}docker-compose.yml
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: optimaai.azurecr.io
          registryUsername: ${{ secrets.OPTIMAAIAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.OPTIMAAIAPI_REGISTRY_PASSWORD }}
          containerAppName: optimaai-api
          resourceGroup: optimaai-rg
          imageToBuild: optimaai.azurecr.io/optimaai-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


